networks:
  app_network:
    driver: bridge

volumes:
  db_data:

services:
  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    volumes:
      - ./src/frontend/static/:/static/ 
    # ports:
    #   - "8000:8000"
    networks:
      - app_network
    depends_on:
      - celery
      - db

  celery:
    build:
      context: .
      dockerfile: celery_app/Dockerfile
    networks:
      - app_network
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    # ports:
    #   - "6379:6379"
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/frontend/static/:/static/ 
    networks:
      - app_network
    depends_on:
      - web
